//! Lane B: the author dossier. The target property is "no human answers for
//! this PR", measured from the author's public record: abandonment after
//! review, provenance markers, latency fingerprints, account shape.
//!
//! One GraphQL query builds the whole dossier (about one rate-limit point);
//! results are cached by the store with a TTL.

use crate::engine::Fire;
use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use serde_json::Value;

/// Commit author emails that identify an agent pipeline.
const AGENT_EMAILS: &[&str] = &[
    "noreply@anthropic.com",
    "agent@openclaw.ai",
    "bot@openclaw.ai",
    "devin-ai-integration[bot]@users.noreply.github.com",
    "cursoragent@cursor.com",
    "codex@openai.com",
];

/// `Co-Authored-By` identities that identify an agent.
const AGENT_TRAILER_NAMES: &[&str] = &[
    "claude", "chatgpt", "copilot", "openclaw", "devin", "cursor", "codex", "aider", "sweep",
    "gemini", "jules",
];

/// PR body / commit footers left by generators.
const GENERATION_FOOTERS: &[&str] = &[
    "generated with [claude code]",
    "generated with claude",
    "generated by openclaw",
    "co-authored with ai",
    "this pr was generated",
    "created by an ai agent",
    "\u{1f916} generated with",
];

/// One historical PR by the author, as far as the dossier cares.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct PriorPr {
    pub merged: bool,
    pub closed_unmerged: bool,
    /// Labels like spam/invalid attached by maintainers.
    pub spam_labeled: bool,
    /// Someone other than the author commented or reviewed.
    pub received_review: bool,
    /// The author said anything at all after that review.
    pub author_followed_up: bool,
    /// Topics/language of the repo, for unrelatedness.
    pub repo_key: String,
}

/// Everything the dossier knows about an author, ready to become rules.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct DossierFacts {
    pub login: String,
    pub account_age_days: Option<i64>,
    pub has_bio: bool,
    pub followers: u64,
    pub restricted_contributions: u64,
    pub prior: Vec<PriorPr>,
    /// Seconds between fork creation and PR open, when the PR is from a fork.
    pub fork_to_pr_secs: Option<i64>,
    /// Lines added in the current PR.
    pub additions: u64,
    /// Median seconds the author takes to reply in threads (needs >= 5).
    pub median_reply_secs: Option<i64>,
    /// Normalized entropy of commit hour-of-day, 1.0 = uniform (needs >= 30).
    pub commit_hour_entropy: Option<f64>,
    /// Provenance markers found in the current PR.
    pub agent_email: bool,
    pub agent_trailer: bool,
    pub generation_footer: bool,
    /// Corroborated network verdict strength in [0,1], from federation.
    pub network_verdict: f64,
    /// GitHub's own spam systems have flagged this account: the search API
    /// refuses to query it ("users cannot be searched") and the PR
    /// connection comes back empty despite visible PRs.
    pub search_blocked: bool,
}

/// Scan commit metadata and PR body for provenance markers.
pub fn scan_markers(
    commit_emails: &[String],
    commit_messages: &[String],
    pr_body: &str,
) -> (bool, bool, bool) {
    let email = commit_emails.iter().any(|e| {
        let e = e.to_lowercase();
        AGENT_EMAILS.iter().any(|a| e == *a)
    });
    let trailer = commit_messages.iter().any(|m| {
        m.to_lowercase().lines().any(|l| {
            let l = l.trim();
            l.starts_with("co-authored-by:") && AGENT_TRAILER_NAMES.iter().any(|n| l.contains(n))
        })
    });
    let body = pr_body.to_lowercase();
    let footer = GENERATION_FOOTERS.iter().any(|f| body.contains(f))
        || commit_messages.iter().any(|m| {
            GENERATION_FOOTERS
                .iter()
                .any(|f| m.to_lowercase().contains(f))
        });
    (email, trailer, footer)
}

impl DossierFacts {
    /// Turn facts into engine rules. Thresholds for "enough data" live here:
    /// a ratio computed over two PRs is noise and stays silent.
    pub fn rules(&self) -> Vec<Fire> {
        let mut out = Vec::new();

        // Abandonment after review: the workhorse.
        let reviewed: Vec<&PriorPr> = self.prior.iter().filter(|p| p.received_review).collect();
        if reviewed.len() >= 3 {
            let abandoned = reviewed.iter().filter(|p| !p.author_followed_up).count();
            out.push(Fire::new(
                "DOSSIER_ABANDONMENT",
                abandoned as f64 / reviewed.len() as f64,
            ));
        }

        let total = self.prior.len();
        if total >= 5 {
            let closed = self.prior.iter().filter(|p| p.closed_unmerged).count();
            out.push(Fire::new(
                "DOSSIER_CLOSED_RATIO",
                closed as f64 / total as f64,
            ));
        }

        let spam = self.prior.iter().filter(|p| p.spam_labeled).count();
        if spam > 0 {
            out.push(Fire::new(
                "DOSSIER_SPAM_LABELS",
                (spam as f64 / 3.0).min(1.0),
            ));
        }

        if self.agent_email {
            out.push(Fire::hit("AGENT_EMAIL"));
        }
        if self.agent_trailer {
            out.push(Fire::hit("AGENT_TRAILER"));
        }
        if self.generation_footer {
            out.push(Fire::hit("GENERATION_FOOTER"));
        }

        if let Some(secs) = self.fork_to_pr_secs {
            if self.additions >= 50 && (0..3600).contains(&secs) {
                // 0s -> 1.0, one hour -> 0.0.
                out.push(Fire::new("VELOCITY_FORK_TO_PR", 1.0 - secs as f64 / 3600.0));
            }
        }

        if let Some(median) = self.median_reply_secs {
            if median < 60 {
                out.push(Fire::hit("REPLY_INSTANT"));
            }
        }

        if let Some(entropy) = self.commit_hour_entropy {
            if entropy > 0.97 {
                out.push(Fire::new("HOUR_ENTROPY_FLAT", entropy));
            }
        }

        if let Some(age) = self.account_age_days {
            if age < 30 {
                out.push(Fire::new("ACCOUNT_NEW", 1.0 - age as f64 / 30.0));
            }
        }

        // Opaque account: nothing public to know the person by.
        if !self.has_bio && self.followers == 0 && self.restricted_contributions > 0 {
            out.push(Fire::hit("ACCOUNT_OPAQUE"));
        }

        // Unrelatedness: many distinct repos, no repetition.
        if total >= 5 {
            let mut keys: Vec<&str> = self.prior.iter().map(|p| p.repo_key.as_str()).collect();
            keys.sort_unstable();
            keys.dedup();
            let spread = keys.len() as f64 / total as f64;
            if spread > 0.8 {
                out.push(Fire::new("UNRELATED_SPREAD", spread));
            }
        }

        if self.network_verdict > 0.0 {
            out.push(Fire::new("NETWORK_AUTHOR_VERDICT", self.network_verdict));
        }

        if self.search_blocked {
            out.push(Fire::hit("GH_FLAGGED"));
        }

        out
    }
}

/// The single GraphQL query that builds a dossier.
pub fn dossier_query(login: &str) -> Value {
    serde_json::json!({
        "query": DOSSIER_GQL,
        "variables": { "login": login }
    })
}

pub const DOSSIER_GQL: &str = r#"
query($login: String!) {
  user(login: $login) {
    createdAt
    bio
    followers { totalCount }
    contributionsCollection { restrictedContributionsCount }
    pullRequests(last: 50) {
      nodes {
        state
        merged
        createdAt
        labels(first: 10) { nodes { name } }
        reviews(first: 1) { totalCount }
        comments(first: 50) { nodes { author { login } createdAt } }
        repository {
          nameWithOwner
          primaryLanguage { name }
        }
      }
    }
  }
}
"#;

/// Parse the GraphQL response into facts. Latency, entropy, markers and the
/// current-PR fields are filled by the caller from other sources.
pub fn parse_dossier(login: &str, response: &Value, now: DateTime<Utc>) -> DossierFacts {
    let user = &response["data"]["user"];
    let mut facts = DossierFacts {
        login: login.to_string(),
        ..Default::default()
    };
    if user.is_null() {
        return facts;
    }

    if let Some(created) = user["createdAt"].as_str() {
        if let Ok(dt) = created.parse::<DateTime<Utc>>() {
            facts.account_age_days = Some((now - dt).num_days());
        }
    }
    facts.has_bio = user["bio"]
        .as_str()
        .map(|b| !b.trim().is_empty())
        .unwrap_or(false);
    facts.followers = user["followers"]["totalCount"].as_u64().unwrap_or(0);
    facts.restricted_contributions = user["contributionsCollection"]
        ["restrictedContributionsCount"]
        .as_u64()
        .unwrap_or(0);

    let spam_names = ["spam", "invalid", "low quality", "low-quality", "slop"];
    if let Some(nodes) = user["pullRequests"]["nodes"].as_array() {
        for pr in nodes {
            let merged = pr["merged"].as_bool().unwrap_or(false);
            let state = pr["state"].as_str().unwrap_or("");
            let labels: Vec<String> = pr["labels"]["nodes"]
                .as_array()
                .map(|ls| {
                    ls.iter()
                        .filter_map(|l| l["name"].as_str())
                        .map(|s| s.to_lowercase())
                        .collect()
                })
                .unwrap_or_default();
            let reviews = pr["reviews"]["totalCount"].as_u64().unwrap_or(0);
            let comments = pr["comments"]["nodes"]
                .as_array()
                .cloned()
                .unwrap_or_default();
            let others_commented = comments
                .iter()
                .any(|c| c["author"]["login"].as_str().unwrap_or("") != login);
            let received_review = reviews > 0 || others_commented;

            // Did the author say anything after the first non-author comment?
            let first_other = comments
                .iter()
                .filter(|c| c["author"]["login"].as_str().unwrap_or("") != login)
                .filter_map(|c| c["createdAt"].as_str())
                .filter_map(|s| s.parse::<DateTime<Utc>>().ok())
                .min();
            let author_followed_up = match first_other {
                Some(t0) => comments.iter().any(|c| {
                    c["author"]["login"].as_str().unwrap_or("") == login
                        && c["createdAt"]
                            .as_str()
                            .and_then(|s| s.parse::<DateTime<Utc>>().ok())
                            .map(|t| t > t0)
                            .unwrap_or(false)
                }),
                None => false,
            };

            facts.prior.push(PriorPr {
                merged,
                closed_unmerged: state == "CLOSED" && !merged,
                spam_labeled: labels.iter().any(|l| spam_names.contains(&l.as_str())),
                received_review,
                author_followed_up,
                repo_key: pr["repository"]["nameWithOwner"]
                    .as_str()
                    .unwrap_or("")
                    .to_string(),
            });
        }
    }
    facts
}

/// Normalized entropy of commit hours: 1.0 means uniform around the clock.
pub fn hour_entropy(hours: &[u32]) -> Option<f64> {
    if hours.len() < 30 {
        return None;
    }
    let mut counts = [0u32; 24];
    for &h in hours {
        counts[(h % 24) as usize] += 1;
    }
    let n = hours.len() as f64;
    let mut entropy = 0.0;
    for c in counts {
        if c > 0 {
            let p = c as f64 / n;
            entropy -= p * p.log2();
        }
    }
    Some(entropy / (24.0f64).log2())
}

#[cfg(test)]
mod tests {
    use super::*;
    use chrono::TimeZone;

    fn now() -> DateTime<Utc> {
        Utc.timestamp_opt(1_750_000_000, 0).unwrap()
    }

    fn abandoner() -> DossierFacts {
        DossierFacts {
            login: "ghost".into(),
            account_age_days: Some(900),
            has_bio: false,
            followers: 0,
            restricted_contributions: 40,
            prior: (0..10)
                .map(|i| PriorPr {
                    merged: false,
                    closed_unmerged: true,
                    spam_labeled: i < 2,
                    received_review: true,
                    author_followed_up: false,
                    repo_key: format!("org{i}/repo{i}"),
                })
                .collect(),
            ..Default::default()
        }
    }

    #[test]
    fn abandoner_fires_the_workhorse_rules() {
        let rules = abandoner().rules();
        let get = |name: &str| rules.iter().find(|f| f.rule == name);
        assert_eq!(get("DOSSIER_ABANDONMENT").unwrap().value, 1.0);
        assert_eq!(get("DOSSIER_CLOSED_RATIO").unwrap().value, 1.0);
        assert!(get("DOSSIER_SPAM_LABELS").unwrap().value > 0.5);
        assert!(get("ACCOUNT_OPAQUE").is_some());
        assert!(get("UNRELATED_SPREAD").is_some());
        // Old account: newness must not fire.
        assert!(get("ACCOUNT_NEW").is_none());
    }

    #[test]
    fn healthy_contributor_fires_almost_nothing() {
        let facts = DossierFacts {
            login: "regular".into(),
            account_age_days: Some(1200),
            has_bio: true,
            followers: 25,
            prior: (0..10)
                .map(|i| PriorPr {
                    merged: i % 2 == 0,
                    closed_unmerged: false,
                    spam_labeled: false,
                    received_review: true,
                    author_followed_up: true,
                    repo_key: "same/repo".into(),
                })
                .collect(),
            ..Default::default()
        };
        let rules = facts.rules();
        // Abandonment fires at value 0.0 (all followed up); nothing else.
        assert!(rules
            .iter()
            .all(|f| f.rule == "DOSSIER_ABANDONMENT" || f.rule == "DOSSIER_CLOSED_RATIO"));
        assert!(rules.iter().all(|f| f.value == 0.0));
    }

    #[test]
    fn thin_history_stays_silent() {
        let facts = DossierFacts {
            login: "newbie".into(),
            account_age_days: Some(400),
            has_bio: true,
            prior: vec![PriorPr {
                received_review: true,
                author_followed_up: false,
                ..Default::default()
            }],
            ..Default::default()
        };
        // One reviewed PR is not a pattern.
        assert!(facts.rules().is_empty());
    }

    #[test]
    fn new_account_scales_with_age() {
        let mut facts = DossierFacts {
            account_age_days: Some(0),
            has_bio: true,
            ..Default::default()
        };
        let v0 = facts
            .rules()
            .iter()
            .find(|f| f.rule == "ACCOUNT_NEW")
            .unwrap()
            .value;
        assert_eq!(v0, 1.0);
        facts.account_age_days = Some(15);
        let v15 = facts
            .rules()
            .iter()
            .find(|f| f.rule == "ACCOUNT_NEW")
            .unwrap()
            .value;
        assert!((v15 - 0.5).abs() < 1e-9);
    }

    #[test]
    fn velocity_needs_size_and_speed() {
        let mut facts = DossierFacts {
            fork_to_pr_secs: Some(42),
            additions: 200,
            ..Default::default()
        };
        let v = facts
            .rules()
            .iter()
            .find(|f| f.rule == "VELOCITY_FORK_TO_PR")
            .unwrap()
            .value;
        assert!(v > 0.98);
        // Small diff: no velocity signal (forking to fix a typo fast is human).
        facts.additions = 3;
        assert!(facts
            .rules()
            .iter()
            .all(|f| f.rule != "VELOCITY_FORK_TO_PR"));
    }

    #[test]
    fn marker_scan_finds_each_kind() {
        let (e, t, f) = scan_markers(
            &["dev@example.com".into(), "noreply@anthropic.com".into()],
            &["fix: thing\n\nCo-Authored-By: Claude <noreply@anthropic.com>".into()],
            "Regular body\n\n\u{1f916} Generated with Claude Code",
        );
        assert!(e && t && f);
        let (e, t, f) = scan_markers(
            &["dev@example.com".into()],
            &["fix: thing\n\nCo-Authored-By: Jane Doe <jane@example.com>".into()],
            "plain body",
        );
        assert!(!e && !t && !f);
    }

    #[test]
    fn hour_entropy_flat_vs_office_hours() {
        let flat: Vec<u32> = (0..48).map(|i| i % 24).collect();
        assert!(hour_entropy(&flat).unwrap() > 0.99);
        let office: Vec<u32> = (0..40).map(|i| 9 + (i % 8)).collect();
        assert!(hour_entropy(&office).unwrap() < 0.7);
        assert!(hour_entropy(&[1, 2, 3]).is_none());
    }

    #[test]
    fn parse_dossier_full_fixture() {
        let resp: Value = serde_json::json!({
            "data": { "user": {
                "createdAt": "2022-09-01T00:00:00Z",
                "bio": null,
                "followers": { "totalCount": 0 },
                "contributionsCollection": { "restrictedContributionsCount": 120 },
                "pullRequests": { "nodes": [
                    {
                        "state": "CLOSED", "merged": false,
                        "createdAt": "2026-01-01T00:00:00Z",
                        "labels": { "nodes": [ { "name": "Invalid" } ] },
                        "reviews": { "totalCount": 1 },
                        "comments": { "nodes": [
                            { "author": { "login": "maintainer" }, "createdAt": "2026-01-02T00:00:00Z" }
                        ] },
                        "repository": { "nameWithOwner": "big/project", "primaryLanguage": { "name": "Rust" } }
                    },
                    {
                        "state": "MERGED", "merged": true,
                        "createdAt": "2026-02-01T00:00:00Z",
                        "labels": { "nodes": [] },
                        "reviews": { "totalCount": 1 },
                        "comments": { "nodes": [
                            { "author": { "login": "maintainer" }, "createdAt": "2026-02-02T00:00:00Z" },
                            { "author": { "login": "ghost" }, "createdAt": "2026-02-03T00:00:00Z" }
                        ] },
                        "repository": { "nameWithOwner": "other/repo", "primaryLanguage": { "name": "Go" } }
                    }
                ] }
            } }
        });
        let facts = parse_dossier("ghost", &resp, now());
        assert!(facts.account_age_days.unwrap() > 1000);
        assert!(!facts.has_bio);
        assert_eq!(facts.restricted_contributions, 120);
        assert_eq!(facts.prior.len(), 2);
        let first = &facts.prior[0];
        assert!(first.closed_unmerged && first.spam_labeled && first.received_review);
        assert!(!first.author_followed_up);
        let second = &facts.prior[1];
        assert!(second.merged && second.author_followed_up);
    }

    #[test]
    fn parse_dossier_missing_user_is_empty() {
        let resp: Value = serde_json::json!({ "data": { "user": null } });
        let facts = parse_dossier("gone", &resp, now());
        assert!(facts.prior.is_empty());
        assert!(facts.rules().is_empty());
    }

    #[test]
    fn network_verdict_becomes_a_rule() {
        let facts = DossierFacts {
            network_verdict: 0.8,
            ..Default::default()
        };
        let rules = facts.rules();
        assert_eq!(rules.len(), 1);
        assert_eq!(rules[0].rule, "NETWORK_AUTHOR_VERDICT");
        assert!((rules[0].value - 0.8).abs() < 1e-12);
    }
}
